baseURL: "http://tomfern.com"
languageCode: "en-us"
title: "Chaos is order not yet deciphered"
theme: "hugo-theme-mini"

permalinks:
  posts: /posts/:title/

# googleAnalytics: 
# disqusShortname: nodejh

enableEmoji: true

markup:
  highlight:
    guessSyntax: true
    style: emacs

social:
  github: https://github.com/TomFern
  twitter: https://github.com/TomFernBlog
  # stackoverflow: https://github.com/TomFern/

params:
  author: "Tommy — Technical Writer at Semaphore"
  bio: Technical Writer
  enableRSS: true
  enableComments: false
  enableGoogleAnalytics: false
